# Generated by Django 4.1 on 2022-08-26 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
    ]
